site_name: TD
nav:
  - Home: index.md
  - About: about.md
  - Input: input.md
  - Use: use.md
  - Code documentation: td.md

theme:
  name: mkdocs
  navigation_depth: 3

plugins:
  - mkdocstrings:

markdown_extensions:
  - admonition

#theme: readthedocs
copyright: Rainer Strotmann, Jan-2022


